apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    db: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql

  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
        - image: mysql:5.7.8
          name: mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-pass
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              value:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: sql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - name: sqlport
              containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    db: mysql
  ports:
      - port: 3306
